name: Build
on:
  push:
    tags: 
      - machina-wrapper-json/*

env:
  version: 5.35
  target_repo: karashiiro/FFXIVOpcodes
  target_fork: zhyupe/FFXIVOpcodes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: repo

    - name: Clone FFXIVOpcodes
      run: git clone https://github.com/${target_repo}.git machina-wrapper-json
      
    - name: Check node version
      run: node -v
      
    - name: NPM install
      run: |
        cd repo
        npm i
      
    - name: Run data generator
      run: node repo/worker/machina-wrapper-json machina-wrapper-json ${{ env.version }}
      
    - name: Setting origin
      run: |
        cd machina-wrapper-json
        git remote set-url origin https://github.com/${target_repo}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.WORKER_ACCESS_KEY }}
        path: machina-wrapper-json
        commit-message: "feat(ipc): update for cn patch-${{ env.version }}"
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        push-to-fork: ${{ env.target_fork }}
        branch: ci/zh/opcode-patch-${{ env.version }}
        base: master
        title: "feat(ipc): update for cn patch-${{ env.version }}"
        body: |
          This PR is generated by [ffxiv-opcode-worker](https://github.com/zhyupe/ffxiv-opcode-worker)